with retail as (
    select * from {{ ref('stg_retail__weekly_sales') }}
)

select
    {{ dbt_utils.generate_surrogate_key(['week_ending_date', 'upc']) }} as retail_weekly_sales_key,
    week_ending_date,
    fiscal_week,
    file_date,
    upc,
    retailer_item_number,
    item_description,
    retail_price,
    total_sales_ty_units,
    total_sales_ly_units,
    total_sales_units_chg_pct,
    total_sales_ty_dollars,
    total_sales_ly_dollars,
    total_sales_dollars_chg_pct,
    comp_sales_ty_units,
    comp_sales_ly_units,
    comp_sales_units_chg_pct,
    comp_sales_ty_dollars,
    comp_sales_ly_dollars,
    comp_sales_dollars_chg_pct,
    noncomp_sales_ty_units,
    noncomp_sales_ly_units,
    noncomp_sales_units_chg_pct,
    noncomp_sales_ty_dollars,
    noncomp_sales_ly_dollars,
    noncomp_sales_dollars_chg_pct,
    dotcom_sales_ty_units,
    dotcom_sales_ly_units,
    dotcom_sales_units_chg_pct,
    dotcom_sales_ty_dollars,
    dotcom_sales_ly_dollars,
    dotcom_sales_dollars_chg_pct,
    total_eoh_ty_units,
    total_eoh_ly_units,
    dc_eoh_ty_units,
    dc_eoh_ly_units,
    store_eoh_ty_units,
    store_eoh_ly_units,
    store_in_stock_pct
from retail
