name: dtc_brand_analytics
version: '1.0.0'
config-version: 2

profile: dtc_brand_analytics

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dtc_brand_analytics:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table
  elementary:
    +schema: elementary

seeds:
  dtc_brand_analytics:
    product_mapping:
      +column_types:
        pack_size_months: INT64
        is_bundle: BOOLEAN
        active: BOOLEAN
