with src as (
    select * from {{ source('shopify', 'raw_shopify_orders_core_commerce') }}
)

select
    cast(order_id as string) as order_id,
    cast(timestamp as timestamp) as order_timestamp,
    cast(customer_email as string) as customer_email_hash,
    cast(revenue as float64) as revenue,
    cast(quantity as int64) as quantity,
    cast(cost as float64) as cost,
    cast(shipping as float64) as shipping,
    cast(tax as float64) as tax,
    cast(discount as float64) as discount,
    cast(status as string) as order_status,
    cast(day_of_week as string) as day_of_week,
    cast(device as string) as device,
    cast(channel as string) as channel,
    cast(source as string) as source,
    cast(metro as string) as metro,
    cast(campaign as string) as campaign,
    cast(amount_refunded as float64) as amount_refunded,
    cast(current_device as string) as current_device,
    cast(current_channel as string) as current_channel,
    cast(current_source as string) as current_source,
    cast(current_metro as string) as current_metro,
    cast(current_campaign as string) as current_campaign,
    cast(transaction_id as string) as transaction_id,
    cast(gift_card_revenue as float64) as gift_card_revenue,
    cast(is_gift_card as boolean) as is_gift_card,
    cast(order_source as string) as order_source,
    cast(state as string) as state,
    cast(country_code as string) as country_code,
    cast(line_item_count as int64) as line_item_count,
    cast(highest_priced_product as float64) as highest_priced_product,
    cast(lowest_priced_product as float64) as lowest_priced_product,
    cast(currency as string) as currency,
    cast(fulfillment_status as string) as fulfillment_status,
    cast(user_id as string) as user_id,
    cast(user as string) as user,
    cast(location_id as string) as location_id,
    cast(pos_id as string) as pos_id,
    cast(processiong_method as string) as processing_method,
    cast(source_identifier as string) as source_identifier,
    cast(gateway as string) as gateway,
    cast(location as string) as location,
    cast(pos as string) as pos,
    cast(app_id as string) as app_id,
    cast(cancelled_at as timestamp) as cancelled_at,
    cast(closed_at as timestamp) as closed_at,
    cast(cancel_reason as string) as cancel_reason,
    cast(sales_channel_id as string) as sales_channel_id,
    cast(sales_channel as string) as sales_channel,
    cast(customer_id as string) as customer_id

from src
